[features]
seeds = false
skip-lint = false
[programs.localnet]
calculator = "EPYNLybn2msbFu2TFtC6LN5WFgYJgVWDY536v55ggCfJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/asad/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
